from enum import Enum
class APIStatus(Enum):
    UP = "UP"
    DOWN = "DOWN"
    WARN = "WARN"
    NOT_SYNCHRONIZED = "NOT_SYNCHRONIZED"
    SYNCHRONIZED = "SYNCHRONIZED"
    FAILED_SYNCHRONIZATION = "FAILED_SYNCHRONIZATION"