from enum import Enum

class OrganisationResourceType(Enum):
    ALL = "ALL"
    ORGANISATION = "ORGANISATION"
    ORGANISATIONAL_UNIT = "ORGANISATIONAL_UNIT"
    DETAILS = "DETAILS"
    HABILITATION = "HABILITATION"
    CONNECTORS = "CONNECTORS"
    CONNECTIONS = "CONNECTIONS"
    PROJECTS = "PROJECTS"
    APIS = "APIS"
    ENVIRONMENT = "ENVIRONMENT"

class OrganisationalUnitResourceType(Enum):
    ALL = "ALL"
    ORGANISATION = "ORGANISATION"
    DETAILS = "DETAILS"
    HABILITATION = "HABILITATION"
    CONNECTORS = "CONNECTORS"
    CONNECTIONS = "CONNECTIONS"
    PROJECTS = "PROJECTS"
    APIS = "APIS"
    ENVIRONMENT = "ENVIRONMENT"
    ORGANISATIONAL_UNIT = "ORGANISATIONAL_UNIT"